import React, { useEffect, useRef } from 'react';
import DOMPurify from 'dompurify';
import { useNavigate } from 'react-router-dom';

/**
 * PagePilotRenderer Component
 * 
 * Renders HTML content generated by PagePilot inside a Shadow DOM.
 * 
 * Why Shadow DOM?
 * PagePilot pages contain their own global `<style>` blocks (e.g., CSS resets, resets for body/html).
 * Rendering inside Shadow DOM ensures the styles are completely encapsulated and do not pollute
 * or break the parent MERN application.
 * 
 * Why DOMPurify?
 * Shadow DOM is NOT an XSS sandbox (scripts inside Shadow DOM can access host window/document).
 * We sanitize all incoming HTML with DOMPurify before inserting into the shadow root.
 */
const PagePilotRenderer = ({ htmlContent, sections = [] }) => {
  const containerRef = useRef(null);
  const shadowRootRef = useRef(null);
  const navigate = useNavigate();

  // Combine section contents if root htmlContent is not directly provided
  const rawHtml = htmlContent || sections.map(s => s.content || '').join('\n');

  useEffect(() => {
    if (!containerRef.current) return;

    // Attach Shadow DOM if not already attached
    if (!shadowRootRef.current) {
      shadowRootRef.current = containerRef.current.attachShadow({ mode: 'open' });
    }

    const shadow = shadowRootRef.current;

    // 1. Sanitize HTML using DOMPurify
    const sanitizedHtml = DOMPurify.sanitize(rawHtml, {
      ADD_TAGS: ['style', 'link', 'picture'],
      ADD_ATTR: ['target', 'rel', 'data-action', 'data-block', 'data-layout', 'data-ahd-tpl-root', 'role', 'aria-label', 'aria-hidden', 'aria-controls'],
      FORCE_BODY: false,
    });

    // 2. Inject Sanitized HTML into Shadow DOM
    shadow.innerHTML = sanitizedHtml;

    // 3. Intercept internal anchor link clicks to preserve single-page app navigation
    const handleAnchorClick = (event) => {
      // Ignore if click was modified (Ctrl/Cmd/Shift/Alt click) or right-click
      if (event.metaKey || event.ctrlKey || event.shiftKey || event.altKey || event.button !== 0) {
        return;
      }

      const anchor = event.target.closest('a');
      if (!anchor) return;

      const href = anchor.getAttribute('href');
      const target = anchor.getAttribute('target');

      // Do not intercept external targets (_blank), mailto:, tel:, hashes (#), or javascript: links
      if (target === '_blank' || !href || href.startsWith('#') || href.startsWith('mailto:') || href.startsWith('tel:') || href.startsWith('javascript:')) {
        return;
      }

      // If it is a relative internal link (e.g. /about-us or /services)
      if (href.startsWith('/') && !href.startsWith('//')) {
        event.preventDefault();
        navigate(href);
      }
    };

    shadow.addEventListener('click', handleAnchorClick);

    return () => {
      shadow.removeEventListener('click', handleAnchorClick);
    };
  }, [rawHtml, navigate]);

  return (
    <div 
      ref={containerRef} 
      className="shadow-host-container"
      data-testid="pagepilot-shadow-container"
    />
  );
};

export default PagePilotRenderer;
